### ISSUE TITLE
problem after number

### ISSUE THREAD

**Issue by SiNaPsEr0x** [gurland/telegram-delete-all-messages#42]
Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

Traceback (most recent call last):
  File "/home/kali/hack/telegram-delete-all-messages/cleaner.py", line 130, in <module>
    deleter.select_groups()
  File "/home/kali/hack/telegram-delete-all-messages/cleaner.py", line 50, in select_groups
    chats = self.get_all_chats()
  File "/home/kali/hack/telegram-delete-all-messages/cleaner.py", line 42, in get_all_chats
    dialog_chunk = app.get_dialogs()
  File "/home/kali/.local/lib/python3.9/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/kali/.local/lib/python3.9/site-packages/pyrogram/methods/chats/get_dialogs.py", line 96, in get_dialogs
    messages[chat_id] = await types.Message._parse(self, message, users, chats)
  File "/home/kali/.local/lib/python3.9/site-packages/pyrogram/types/messages_and_media/message.py", line 720, in _parse
    parsed_message.reply_to_message = await client.get_messages(
  File "/home/kali/.local/lib/python3.9/site-packages/pyrogram/methods/messages/get_messages.py", line 114, in get_messages
    r = await self.send(rpc, sleep_threshold=-1)
  File "/home/kali/.local/lib/python3.9/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/home/kali/.local/lib/python3.9/site-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/home/kali/.local/lib/python3.9/site-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/home/kali/.local/lib/python3.9/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ChannelPrivate: [400 CHANNEL_PRIVATE]: The channel/supergroup is not accessible (caused by "channels.GetMessages")

**Comment by gurland** [comment]
This bug isn't reproducible and not related to this repository. I'd assume this was a problem on Telegram side or you were kicked/banned or peer was deleted while the script was running.
