### ISSUE TITLE
TypeError: get_dialogs() got an unexpected keyword argument 'pinned_only'

### ISSUE THREAD

**Issue by grdll** [gurland/telegram-delete-all-messages#64]
# pip3 show pyrogram
```
Name: Pyrogram
Version: 2.0.106
```

```
Traceback (most recent call last):
  File "/root/telegram-delete-all-messages/cleaner.py", line 154, in <module>
    deleter.select_groups()
  File "/root/telegram-delete-all-messages/cleaner.py", line 67, in select_groups
    chats = self.get_all_chats()
  File "/root/telegram-delete-all-messages/cleaner.py", line 57, in get_all_chats
    dialogs = app.get_dialogs(pinned_only=True)
  File "/usr/local/lib/python3.9/site-packages/pyrogram/sync.py", line 53, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
TypeError: get_dialogs() got an unexpected keyword argument 'pinned_only'
```

#53 #62

**Comment by ShamblerDK** [comment]
> above version 2.0 the project pyrogram has remove this parameter in function `get_dialogs`. You can read the document to achieve your demand such as filter. And this project use version 1.4, it's not wrong.

The project now requires Pyrogram v2.
