### ISSUE TITLE
I'm going crazy (The msg_id is too low, the client time has to be synchronized.) 

### ISSUE THREAD

**Issue by shaukky** [gurland/telegram-delete-all-messages#76]
Yes I have synced the system, even installed extra syncy things to triple check system time - issue persists. 
Yes I have updated pyrogram - issue persists. 
Yes I have run it in a VM - issue persists. 

"The msg_id is too low, the client time has to be synchronized." brutal and primitive error that for the life of me I can't fix. Shamefully I must ask for help :(

**Comment by Lordovsaba** [comment]
i also have the same issue i have already done sync time date ect and also updated to the latest version of pyrogram version 2.0.106, hope someone finds a fix im pulling my hair out here haha

**Comment by EvgenyKislyy** [comment]
Same here

**Comment by d2avids** [comment]
In my case, i set `time.sleep(2)` at the start of the programm and then turned off VPN. Probably, turning off VPN could have helped initially without setting `time.sleep`.

**Comment by BpArCuCTeMbI** [comment]
Same issue there. Ubuntu 22.04/Python3.10.12

**Comment by Owl-Tec** [comment]
I fixed the issue by doing the following:

- In the "requirements.txt" file I changed the following line to as follows: "pyrogram==1.4" -> "pyrogram==2.0.106"
- Re-ran the "install.bat" file (this was key)

Sadly, looks like the application is broken currently:
```
Traceback (most recent call last):
  File "C:\Users\XXXX\Downloads\telegram-delete-all-messages-master\cleaner.py", line 154, in <module>
    deleter.select_groups()
  File "C:\Users\XXXX\Downloads\telegram-delete-all-messages-master\cleaner.py", line 67, in select_groups
    chats = self.get_all_chats()
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\Downloads\telegram-delete-all-messages-master\cleaner.py", line 57, in get_all_chats
    dialogs = app.get_dialogs(pinned_only=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\Downloads\telegram-delete-all-messages-master\venv\Lib\site-packages\pyrogram\sync.py", line 53, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
```

Edit: fix below here works:
- https://github.com/gurland/telegram-delete-all-messages/issues/70

**Comment by d2avids** [comment]
The app works fine, I'm using it. Just need to play around a bit

**Comment by williamdes** [comment]
See https://github.com/gurland/telegram-delete-all-messages/issues/80#issuecomment-3121664312 for a working PR and solution

**Comment by gurland** [comment]
Closed as #68 was merged.
